### ISSUE TITLE
Save / Cancel buttons on forms invisible on small screens

### ISSUE THREAD

**Issue by mojca** [geomagpy/magpy#65]
I spent a while debugging this, but I still need to figure out how spacers work exactly.

My computer screen is too small, so the default window size `size=(1000, 800)` for `InputSheetDialog` (combined with `size=(950, 750)` `for SettingsPanel`) is efficiently defunct for me unless I patch it locally. The buttons that are necessary to make the input sheet functional are below the sceen. I still didn't figure out how to make the window resizable. I tried using `wx.GROW` on `self.mainSizer.Add`, but I'm probably missing some further instances. From what I understand this should be used on every single spacer.

(I was trying to debug another bug of some spurious elements drawn on the DI input sheet, but it turned out that deleting `~/.magpyguiini` solved the issue. I deleted that file, so finding proper workarounds might be trickier now.)

**Comment by leonro** [comment]
Should work now on all screens (90e32dcc5285b9035814e83a68c6fecd05f7c224).
The window is now resizeable. Need to add this feature to all other large windows as well. 
Magpyguiini should be automatically updated now if a new version is installed, so that spurious DI input sheet elements will not appear any more. 
Please check. Will close as soon as checked and added to other large dialogs.

**Comment by leonro** [comment]
This issue is solved with 74f9edcae4f996c79494c21f9c1006fc48b912e3 .
I also added the same resizing possibility to the MetaInformation fields and corrected a bug there with multiline fields.
Tested on MacOS 10.12.3.
