### ISSUE TITLE
Merging streams not work 0.4.7c

### ISSUE THREAD

**Issue by teraita** [geomagpy/magpy#97]
Testing of merge 1 minute streams from two instruments ( files have X,YZ and F) to calculate dF. This works fine in older version 0.3.99rc5 , but not anymore in 0.4.7c.

<img width="1395" alt="Merge_streams_0 3 9rc5" src="https://user-images.githubusercontent.com/22149196/64855026-a6156780-d627-11e9-92a8-b99e318a7539.png">
<img width="1719" alt="Merge_streams_0 4 7c" src="https://user-images.githubusercontent.com/22149196/64855027-a6156780-d627-11e9-9631-7141f9dfd04e.png">

**Comment by leonro** [comment]
This issue is related to different treatments of closing dialog windows in different operating systems. The current issue only affects MacOS. In order to solve this issue i am currently working on a rather "complete" solution within branch merge-fix. In order to get rid of such effects, (1) magpy is getting now fully python3 compatible, (2) supports wx4.x. Within merge-fix I am also merging Heathers and Jeremies corrections and extensions from their pull request into the code.

**Comment by leonro** [comment]
Issue is fixed from 0.9.3 onwards
